server:
  port: 8080

zuul:
  routes:
    api:
      url: http://localhost:8100

spring:
  application:
    name: zuul-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url: http://locahost:8080/status
#    health-check-url-path: http://locahost:8080/headlth